name: Newsight
favicon: null
layout_spectrum: 0.3355891243554652
typography_spectrum: 0.33141268393956125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.868820289382711
  lightness: 0.0437317481264472
  saturation: 0.35141231399029493
  rhythmicContrast: 0.3255200223065913
purpose: []
